### ISSUE TITLE
Gradle structure

### ISSUE THREAD

**Issue by 2Pit** [StepicOrg/intellij-plugins#15]
Сообщение от @taery:

@2Pit, ты спрашивал про структуру. Что я хочу:
1. Ок, пусть будет проект, в котором много модулей(пожалуй, так даже лучше, пусть ядро будет отдельным модулем, который при желании можно отключить и использовать родное ядро). И если сделать правильную структуру - не надо будет менять пути к ресурсам, так как пути останутся те же. Единственное, точно будет конфликт, так как остается зависимость от плагина - нужно хорошо эксклюды прописать, чтобы не было конфликтов. Я могу попробовать помочь с эксклюдами, если к нашему митингу завтра, будет что-то рабочее - давайте для этого сегодня разберемся со структурой, чтобы я могла с нуля выгрузить проект и он сразу заработал.  
2. Каждый модуль должен иметь следующую структуру 

```
src
    -main
        -java
        -resources
    -test
        -java
        -resources
```

И ты, и @meanmail немного мешаете сущности и это выносит мозг. (@meanmail, я про один уровень `core` и `main`)

В итоге, package-ы с кодом лежат всегда внутри java, ресурсы в ресурсах. По поводу того, что там должно как быть в ресурсах - обсудим после, сначала давайте общую структуру.

Резюме, проект выглядит так:
2. Каждый модуль должен иметь следующую структуру 

```
intellij-plugins\
  - core\
    -src\
      -main\
          -java\
          -resources\
      -test\
          -java\
          -resources\
  - stepik-union\
    -src\
      -main\
          -java\
          -resources\
      -test\
          -java\
          -resources\
  -src  \\ этой части может не быть, если она не нужна. 
      -main\
          -java\
          -resources\
      -test\
          -java\
          -resources\

```

**Comment by taery** [comment]
@meanmail, я дала тебе права на наш YT, давайте все задачи держать там. Текущий спринт можно смотреть по ссылке https://vyahhi.myjetbrains.com/youtrack/agiles/79-19/81-83 (открывается? если нет - то что у тебя во вкладке agile boards?)

**Comment by taery** [comment]
Перенесла содержимое этой задачи в https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-53

**Comment by meanmail** [comment]
Всё открылось, хорошо =)

**Comment by taery** [comment]
Только если решил делать какую-то задачу, пиши об этом - чтобы все одно и то же одновременно не делали :-)

**Comment by meanmail** [comment]
Эту задачу надо закрепить за мной :)
