### ISSUE TITLE
Task Description

### ISSUE THREAD

**Issue by meanmail** [StepicOrg/intellij-plugins#5]
Смог собрать проект, всё работает.
Но не правильно работает обновление содержимого Task Description.
При открытии новой задачи, появляется описание другой задачи либо вообще не обновляется. Данный баг я внес сам :)

Вопрос собственно вот в чем, по какому событию обновляется Task Description. Вроде это просто, но я что-то упускаю.

**Comment by 2Pit** [comment]
Насколько я помню, никаких событий нет. На Editor вешается Listener, StudyEditorFactoryListener и он следит за тем чтобы при изменении активного окна Editor-a отображался текст новой задачи.

Можно вдобавок посмотреть кто дергает метод StudyUtils.updateToolWindows(Project project);
