### ISSUE TITLE
Bug. Don't remove tabs if removeDirectives

### ISSUE THREAD

**Issue by meanmail** [StepicOrg/intellij-plugins#6]
Если нажимать несколько раз кнопку добавить/убирать обрамляющий класс, то текст между директивами будет сдвигаться вправо.

**Comment by 2Pit** [comment]
Да, есть такая штука. Не знаю как с ней бороться. Просто проверять является ли первый символ табуляцией - плохая идея. По хорошему стоит вызывать над файлом действие "Reformat code", но я не нашёл как это можно сделать.

**Comment by taery** [comment]
@2Pit, а что конкретно у тебя не получилось найти? 
Если я тебе скажу волшебную фразу `ReformatCodeAction`, это поможет? или как раз экшены и не умеешь запускать?

**Comment by taery** [comment]
Да, кстати, с самого начала вставлять табы - плохая идея. Это очень раздражает, особенно в джаве, где идея тебе все помечает желтым из-за табов. 
@2Pit можно сделать из этого отдельную задачу.

**Comment by taery** [comment]
@meanmail, создала отдельную [задачу](https://github.com/StepicOrg/intellij-plugins/issues/8), возьмешься за реализацию? А этот PR пусть пока повисит, только постарайся не мешать особо рефакторинг с конкретной проблемой. Если PR будет решать какую-то одну конкретную задачу, вероятность вмержить его выше.

**Comment by meanmail** [comment]
Возьмусь

**Comment by meanmail** [comment]
По поводу окружающего кода. Думаю его нужно сохранять где-то в отдельном скрытом файле, если пользователь изменил внешний код. Тогда можно будет, не задавая лишних вопросов, убирать внешний код.

**Comment by taery** [comment]
не, сейчас так точно не надо делать.

**Comment by 2Pit** [comment]
> Да, кстати, с самого начала вставлять табы - плохая идея.

Можно убрать. Тогда и код на платформе отображаться лучше будет.
