### ISSUE TITLE
Auto run Reformat code 

### ISSUE THREAD

**Issue by taery** [StepicOrg/intellij-plugins#8]
Нужно при всех автоматических генерациях уметь запускать автоматический реформат. 
Возможно, класс `com.intellij.codeInsight.actions.ReformatCodeAction` чем-нибудь поможет

**Comment by meanmail** [comment]
Возьмусь за эту задачу.

**Comment by taery** [comment]
как тут по-дурацки задачи закрываются однако.

**Comment by meanmail** [comment]
Я думал это должно происходить автоматически
